import java.io.IOException;

import com.sumit.Book;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/AddBookServlet")
public class AddBookServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    private BookDao bookDao;

    public void init() {
        bookDao = new BookDao();
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String title = request.getParameter("title");
        String author = request.getParameter("author");
        double price = Double.parseDouble(request.getParameter("price"));
        int quantity = Integer.parseInt(request.getParameter("quantity"));

        // No need to pass id since it's auto-generated by the database
        Book book = new Book(null, title, author, price, quantity);

        boolean added = bookDao.addBook(book);

        if (added) {
            response.sendRedirect("admin-dashboard.jsp?message=Book added successfully.");
        } else {
            response.sendRedirect("admin-dashboard.jsp?error=Failed to add book.");
        }
    }
}
